server:
  port: 8081


spring:
  application:
    name: TWITTER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/twitter
    username: root
    password: neel
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect